#pragma config(Sensor, in1,    lineTracker,    sensorLineFollower)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl11, red,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           firstMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	Project Title: First Sample
	*/


task main()
{

SensorValue(green) = 1;	// this turns on the led in digital port 11; you canm also give it the variable name (red).
SensorValue(red) = 0;


	while(1) {


		while(SensorValue(limitSwitch) == 1 && SensorValue(green) == 1)
		{
			setMotor(port1, 60);

			// motor[firstMotor] = 100; // wait for gas pedal
			//	wait1Msec(9000);

			// start right motor in reverse.
			// wait for breaks pedal
			// stop right motor in reverse.
			// stop left motor in reverse
		//	if(SensorValue(bumpSwitch) == 1) SensorValue(red) = true;
			if (SensorValue(bumpSwitch) == 1)
			{
					stopAllMotors();
					SensorValue(red) = 1;
					SensorValue(green) = 0;
					wait1Msec(1000);
				}
		}


/*
		if(SensorValue(bumpSwitch) == 1){
			stopAllMotors();

		}
		if(SensorValue(bumpSwitch) == 1 && SensorValue(red) == true){
			SensorValue(red) = false;
			SensorValue(green) = true;
		}
		*/
	}

}
