#pragma config(Sensor, in1,    lineTracker,    sensorLineFollower)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           firstMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard  !!*//

/*
	Project Title: First Sample
	*/


task main()
{

	while(1) {

		if(SensorValue(limitSwitch) == 1)
		{
			SensorValue(green) = false;
			setMotor(port1, 60);
			// motor[firstMotor] = 100; // wait for gas pedal
			//	wait1Msec(9000);

			// start right motor in reverse.
			// wait for breaks pedal
			// stop right motor in reverse.
			// stop left motor in reverse
		} else { stopAllMotors(); }

		if(SensorValue(bumpSwitch) == 1){
			stopAllMotors();
			SensorValue(green) = true;
		}
}

}
