#pragma config(Sensor, in1,    lineTracker,    sensorLineFollower)
#pragma config(Sensor, dgtl1,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl2,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl11, red,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           firstMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	Project Title: First Sample
	*/


task main()
{

SensorValue(dgtl12) = 1;	// this turns on the led in digital port 11; you canm also give it the variable name (red).
SensorValue(dgtl11) = 0;


	while(1) {


		if(SensorValue(bumpSwitch) == 1 && SensorValue(limitSwitch) != true)
		{
			SensorValue(green) = true;
			SensorValue(red) = false;
			setMotor(port1, 60);	// this starts the motor when the limitSwitch and red diode is off

		} else { stopAllMotors(); }	// this stops the motor in any other case (mainly the limit switch not being pressed in)

		if(SensorValue(limitSwitch) == 1){
			stopAllMotors();
			SensorValue(red) = true;	// here using the variable-looks cleaner.
			SensorValue(green) = false;
		}

}

}
